logging.level.org.springframework.security: DEBUG
server:
  port: 8081
security: 
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token